// Content script core - orchestrates scraping, classification, overlay
(function() {
  const SCRAPE_INTERVAL = 5000;
  const BATCH_SIZE = 5;
  let overlayEnabled = true;
  let processedIds = new Set();

  async function scrapeAndClassify() {
    const scraper = window.MANIPULATION_AUDITOR_SCRAPER;
    if (!scraper) return;

    const items = scraper.getFeedItems();
    const newItems = items.filter((item) => {
      const id = item.isWatching ? `watch-${item.text?.substring(0, 40)}` : `${item.position}-${item.text?.substring(0, 50)}`;
      return !processedIds.has(id);
    }).slice(0, BATCH_SIZE);

    for (const item of newItems) {
      if (!item.text && (item.title || item.description)) {
        item.text = [item.title, item.description].filter(Boolean).join(' | ');
      }
      const id = item.isWatching ? `watch-${item.text?.substring(0, 40)}` : `${item.position}-${item.text?.substring(0, 50)}`;
      processedIds.add(id);

      const classification = await classifyContent(item);
      if (classification) {
        item.classification = classification;
        chrome.runtime.sendMessage({ type: 'STORE_CONTENT', data: item }).catch(() => {});
        if (overlayEnabled) {
          var el = item.element && item.element.isConnected ? item.element : null;
          if (!el && typeof scraper.getCardElementAtPosition === 'function' && item.position >= 0) {
            el = scraper.getCardElementAtPosition(item.position);
          }
          if (el) {
            addOverlayTag(el, classification);
          } else if (typeof scraper.getCardElementAtPosition === 'function' && item.position >= 0) {
            setTimeout(function () {
              var retryEl = scraper.getCardElementAtPosition(item.position);
              if (retryEl) addOverlayTag(retryEl, classification);
            }, 250);
          }
        }
      }
    }
  }

  async function classifyContent(item) {
    var text = item.text || [item.title, item.description].filter(Boolean).join(' | ');
    if (!text) return fallbackClassify(item);
    try {
      if (!chrome.runtime?.id) return fallbackClassify(item);
      const response = await chrome.runtime.sendMessage({
        type: 'CLASSIFY_CONTENT',
        content: text,
        title: item.title,
        description: item.description,
        isAd: item.isAd,
      });
      var classification = response?.classification || fallbackClassify(item);
      classification = applyManipulationOverride(classification, text);
      return classification;
    } catch (e) {
      return fallbackClassify(item);
    }
  }

  function isStemOrEducational(text) {
    const t = (text || '').toLowerCase();
    return /\b(stem|science|math|physics|chemistry|biology|biological|engineering|medical|medicine|medicinal|anatomy|physiology|tutorial|lesson|course|learn|education|educational|explainer|documentary|facts|research|experiment|khan|crash course|ted\b|tedx|how it works|algebra|calculus|organic chemistry|cartilage|ligament|tendon|parkinson|tremor|clinical)\b/i.test(t) || /stem|interestingstem/.test(t);
  }

  function hasManipulationSignals(text) {
    const t = (text || '').toLowerCase();
    const scam = /\b(scam|act now|limited time|don't miss out|you won't believe|secret|exposed|make money fast|free money|get rich|last chance|order now|buy now|limited offer|guaranteed|earn \d+|they're hiding|before it's too late|urgent|instant cash|no credit card|\d+%\s*off)\b/i;
    const aiGen = /\b(ai generated|ai.?generated|generated by ai|made by ai|chatgpt|deepfake|deep fake|ai.?created|created by ai)\b/i;
    const conspiracy = /\b(conspiracy|conspiracies|government cover|cover.?up|false flag|they're lying|mainstream (media )?lying|wake up|deep state|new world order|the narrative)\b/i;
    return scam.test(t) || aiGen.test(t) || conspiracy.test(t);
  }

  function isAiGeneratedSignals(text) {
    return /\b(ai generated|ai.?generated|generated by ai|made by ai|chatgpt|deepfake|deep fake|ai.?created|created by ai)\b/i.test((text || '').toLowerCase());
  }

  function applyManipulationOverride(classification, text) {
    if (!classification || classification.manipulation_mechanic !== 'neutral') return classification;
    if (!hasManipulationSignals(text)) return classification;
    const t = (text || '').toLowerCase();
    const isConspiracy = /\b(conspiracy|cover.?up|false flag|deep state|they're (lying|hiding)|wake.?up)\b/i.test(t);
    const isAi = isAiGeneratedSignals(text);
    let mechanic = 'curiosity_gap';
    if (isConspiracy) mechanic = 'tribal_identity';
    else if (isAi) mechanic = 'ai_generated';
    return {
      ...classification,
      manipulation_mechanic: mechanic,
      manipulation_intensity: Math.max(classification.manipulation_intensity || 0, 72),
    };
  }

  function fallbackClassify(item) {
    const text = (item.text || '').toLowerCase();
    const urgencyWords = ['breaking', 'shocking', 'you won\'t believe', 'secret', 'exposed', 'everyone is talking'];
    const hasUrgency = urgencyWords.some(w => text.includes(w));
    const hasManipulation = hasManipulationSignals(item.text);
    const isAi = hasManipulation && isAiGeneratedSignals(item.text);
    const cat = inferCategoryFromText(item.text);
    const isStemEdu = isStemOrEducational(item.text);
    let mechanic = 'neutral';
    if (item.isAd) mechanic = 'commercial_manipulation';
    else if (hasManipulation) mechanic = item.isAd ? 'commercial_manipulation' : (isAi ? 'ai_generated' : 'curiosity_gap');
    else if (hasUrgency) mechanic = 'curiosity_gap';
    else if (isStemEdu || cat === 'education' || cat === 'how_to' || cat === 'tech') mechanic = 'informational';
    const intensity = item.isAd ? 70 : (hasManipulation ? 68 : (hasUrgency ? 60 : (mechanic === 'informational' ? 15 : 20)));
    return {
      manipulation_mechanic: mechanic,
      manipulation_intensity: intensity,
      urgency_signals: hasUrgency || hasManipulation,
      content_category: cat,
    };
  }
  function inferCategoryFromText(text) {
    const t = (text || '').toLowerCase();
    if (/\bnews\b|breaking|headline|reporter/i.test(t)) return 'news';
    if (/\bgame|gaming|playthrough|minecraft|fortnite|gamer\b/i.test(t)) return 'gaming';
    if (/\bhow to|tutorial|learn|step by step|guide\b/i.test(t)) return 'how_to';
    if (/\bcomedy|funny|laugh|joke\b/i.test(t)) return 'comedy';
    if (/\bmusic|song|album|lyrics|artist\b/i.test(t)) return 'music';
    if (/\bsport|nba|nfl|soccer|football|basketball\b/i.test(t)) return 'sports';
    if (/\btech|programming|coding|software|developer\b/i.test(t)) return 'tech';
    if (/\beducation|school|study|course|science\b/i.test(t)) return 'education';
    if (/\blifestyle|fitness|recipe|cooking|travel|vlog\b/i.test(t)) return 'lifestyle';
    if (/\bpolitics|democrat|republican|election\b/i.test(t)) return 'politics';
    return 'entertainment';
  }

  function addOverlayTag(element, classification) {
    if (element.querySelector('.ma-overlay-tag')) return;

    const tag = document.createElement('div');
    tag.className = 'ma-overlay-tag';
    const mechanic = classification.manipulation_mechanic || 'neutral';
    const color = MANIPULATION_AUDITOR?.CATEGORY_COLORS?.[mechanic] || '#6b7280';
    const specificLabel = mechanic === 'ai_generated' ? 'AI' : mechanic.replace(/_/g, ' ');
    tag.style.backgroundColor = color;
    const displayText = mechanic === 'neutral' ? 'Neutral' : (mechanic === 'informational' ? 'Informational' : (mechanic === 'ai_generated' ? 'AI' : 'Manipulation'));
    tag.textContent = displayText;
    tag.title = mechanic === 'ai_generated' ? 'AI · ' + (classification.manipulation_intensity || 0) + '% intensity (counts as manipulative)' : specificLabel + ' · ' + (classification.manipulation_intensity || 0) + '% intensity';
    
    element.style.position = 'relative';
    element.appendChild(tag);
  }

  function init() {
    chrome.storage.local.get(['ma_overlay_enabled'], (r) => {
      overlayEnabled = r.ma_overlay_enabled !== false;
    });
    chrome.storage.onChanged.addListener((changes, area) => {
      if (changes.ma_overlay_enabled) {
        overlayEnabled = changes.ma_overlay_enabled.newValue !== false;
      }
    });

    scrapeAndClassify();
    setTimeout(scrapeAndClassify, 2000);
    setTimeout(scrapeAndClassify, 4500);
    setInterval(scrapeAndClassify, SCRAPE_INTERVAL);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
